import re
import markdown
from pathlib import Path
from typing import Optional, List, Dict, Any

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        @page {{
            size: A4;
            margin: 20mm;
        }}
        body {{
            font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            margin: 0;
            padding: 2rem;
            background-color: #ffffff;
        }}
        h1 {{
            color: #0f172a;
            font-size: 2.25rem;
            border-bottom: 3px solid #10b981;
            padding-bottom: 0.5rem;
            margin-top: 0;
        }}
        h2 {{
            color: #1e3a8a;
            font-size: 1.5rem;
            margin-top: 1.75rem;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 0.25rem;
        }}
        h3 {{
            color: #2563eb;
            font-size: 1.2rem;
        }}
        blockquote {{
            background: #f0fdf4;
            border-left: 4px solid #10b981;
            margin: 1rem 0;
            padding: 0.75rem 1rem;
            color: #047857;
        }}
        code {{
            background: #f1f5f9;
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            font-family: monospace;
            font-size: 0.9em;
        }}
        pre {{
            background: #0f172a;
            color: #f8fafc;
            padding: 1rem;
            border-radius: 8px;
            overflow-x: auto;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1.5rem 0;
        }}
        th, td {{
            border: 1px solid #cbd5e1;
            padding: 0.6rem 0.8rem;
            text-align: left;
        }}
        th {{
            background-color: #f8fafc;
            color: #0f172a;
        }}
        .footer {{
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid #e2e8f0;
            font-size: 0.85rem;
            color: #64748b;
            text-align: center;
        }}
    </style>
</head>
<body>
    {content}
    <div class="footer">
        Generated by DeepResearch Studio (NVIDIA NIM + SQLite Evidence Store)
    </div>
</body>
</html>
"""

def markdown_to_html(markdown_text: str, title: str = "Research Report") -> str:
    html_body = markdown.markdown(
        markdown_text,
        extensions=["tables", "fenced_code", "toc", "attr_list"]
    )
    return HTML_TEMPLATE.format(title=title, content=html_body)

def safe_xml_text(raw_text: str) -> str:
    """Escapes XML and converts markdown formatting safely for ReportLab."""
    if not raw_text:
        return ""
    # 1. Escape ampersands and angle brackets
    text = raw_text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    # 2. Markdown formatting to ReportLab tags
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    text = re.sub(r'`(.*?)`', r'<font face="Courier">\1</font>', text)
    return text

def generate_pdf_from_markdown(markdown_text: str, output_pdf_path: Path, title: str = "Research Report"):
    """Generates a publication-quality PDF using ReportLab with guaranteed error-fallback."""
    try:
        doc = SimpleDocTemplate(
            str(output_pdf_path),
            pagesize=A4,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#0f172a'),
            fontName='Helvetica-Bold',
            spaceAfter=10
        )

        h2_style = ParagraphStyle(
            'DocH2',
            parent=styles['Heading2'],
            fontSize=12,
            leading=16,
            textColor=colors.HexColor('#1e3a8a'),
            fontName='Helvetica-Bold',
            spaceBefore=12,
            spaceAfter=5
        )

        h3_style = ParagraphStyle(
            'DocH3',
            parent=styles['Heading3'],
            fontSize=10.5,
            leading=14,
            textColor=colors.HexColor('#059669'),
            fontName='Helvetica-Bold',
            spaceBefore=8,
            spaceAfter=3
        )

        body_style = ParagraphStyle(
            'DocBody',
            parent=styles['Normal'],
            fontSize=9,
            leading=13,
            textColor=colors.HexColor('#334155'),
            fontName='Helvetica',
            spaceAfter=5
        )

        callout_style = ParagraphStyle(
            'DocCallout',
            parent=styles['Normal'],
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor('#047857'),
            fontName='Helvetica-Oblique',
            backColor=colors.HexColor('#ecfdf5'),
            borderColor=colors.HexColor('#10b981'),
            borderWidth=1,
            borderPadding=6,
            spaceBefore=6,
            spaceAfter=6
        )

        table_cell_style = ParagraphStyle(
            'TableCell',
            parent=styles['Normal'],
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor('#1e293b'),
            fontName='Helvetica'
        )

        table_header_style = ParagraphStyle(
            'TableHeaderCell',
            parent=styles['Normal'],
            fontSize=8,
            leading=10.5,
            textColor=colors.HexColor('#0f172a'),
            fontName='Helvetica-Bold'
        )

        story = []
        lines = markdown_text.split('\n')
        in_table = False
        table_rows = []

        printable_width = A4[0] - 72  # 523 points

        def flush_table():
            nonlocal in_table, table_rows
            if not table_rows:
                return
            formatted_table_data = []
            max_cols = max(len(r) for r in table_rows)
            col_width = printable_width / max(max_cols, 1)

            for r_idx, row in enumerate(table_rows):
                formatted_row = []
                for cell_idx in range(max_cols):
                    cell = row[cell_idx] if cell_idx < len(row) else ""
                    st = table_header_style if r_idx == 0 else table_cell_style
                    clean_cell = safe_xml_text(cell.strip())
                    formatted_row.append(Paragraph(clean_cell, st))
                formatted_table_data.append(formatted_row)
            
            t = Table(formatted_table_data, colWidths=[col_width] * max_cols)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
                ('TOPPADDING', (0, 0), (-1, -1), 3),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
                ('LEFTPADDING', (0, 0), (-1, -1), 4),
                ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ]))
            story.append(Spacer(1, 4))
            story.append(t)
            story.append(Spacer(1, 6))
            table_rows = []
            in_table = False

        for line in lines:
            raw_line = line.strip()

            if raw_line.startswith('|') and raw_line.endswith('|'):
                if re.match(r'^\|[\s\-:|]+\|$', raw_line):
                    continue
                cells = [c.strip() for c in raw_line.split('|')[1:-1]]
                if cells:
                    in_table = True
                    table_rows.append(cells)
                    continue
            else:
                if in_table:
                    flush_table()

            if not raw_line:
                continue

            if raw_line.startswith('# '):
                story.append(Paragraph(safe_xml_text(raw_line[2:]), title_style))
                story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#10b981'), spaceAfter=8))
            elif raw_line.startswith('## '):
                story.append(Spacer(1, 4))
                story.append(Paragraph(safe_xml_text(raw_line[3:]), h2_style))
                story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#e2e8f0'), spaceAfter=4))
            elif raw_line.startswith('### '):
                story.append(Paragraph(safe_xml_text(raw_line[4:]), h3_style))
            elif raw_line.startswith('> '):
                story.append(Paragraph(safe_xml_text(raw_line[2:].strip()), callout_style))
            elif raw_line.startswith('- ') or raw_line.startswith('* '):
                story.append(Paragraph(f"• {safe_xml_text(raw_line[2:])}", body_style))
            else:
                story.append(Paragraph(safe_xml_text(raw_line), body_style))

        if in_table:
            flush_table()

        doc.build(story)

    except Exception as e:
        print(f"[PDFExporter] Standard render failed ({e}), building safe fallback PDF...")
        # Guaranteed plain fallback doc
        doc = SimpleDocTemplate(str(output_pdf_path), pagesize=A4, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()
        p_style = ParagraphStyle('Fallback', parent=styles['Normal'], fontSize=9, leading=12)
        fallback_story = [Paragraph(f"<b>{safe_xml_text(title)}</b>", styles['Heading1']), Spacer(1, 10)]
        for l in markdown_text.split('\n'):
            if l.strip():
                clean_l = safe_xml_text(l.strip())
                fallback_story.append(Paragraph(clean_l, p_style))
                fallback_story.append(Spacer(1, 2))
        doc.build(fallback_story)

def export_report_files(session_id: str, markdown_text: str, output_dir: Path) -> dict:
    output_dir.mkdir(parents=True, exist_ok=True)
    
    md_file = output_dir / f"report_{session_id}.md"
    html_file = output_dir / f"report_{session_id}.html"
    pdf_file = output_dir / f"report_{session_id}.pdf"
    
    md_file.write_text(markdown_text, encoding="utf-8")
    
    html_content = markdown_to_html(markdown_text, title=f"Research Report - {session_id}")
    html_file.write_text(html_content, encoding="utf-8")

    try:
        generate_pdf_from_markdown(markdown_text, pdf_file, title=f"Research Report - {session_id}")
    except Exception as e:
        print(f"[PDFExporter] Error generating ReportLab PDF: {e}")
    
    return {
        "markdown_path": str(md_file),
        "html_path": str(html_file),
        "pdf_path": str(pdf_file)
    }
